from .Downloader import *

class SkySportsDownloader(Downloader):
    def __init__(self):
      self.url = "https://www.skysports.com/calendars/football/fixtures/teams/birmingham-city"

    def download(self):
        icsFileContents = requests.get(self.url).text
        calendar = Calendar(icsFileContents)
        icsFileName = "GenCal Calendar"
        icsFileDescription = "This calendar was generated by the Gencal App"
        icsFileContents = "\r\n".join(
           f"X-WR-CALNAME:{icsFileName}" if line.startswith("X-WR-CALNAME") 
           else f"NAME:{icsFileName}" if line.startswith("NAME") 
           else f"X-WR-CALDESC:{icsFileDescription}" if line.startswith("X-WR-CALDESC") 
           else line
           for line in calendar.serialize().splitlines()
           )
        calendar = Calendar(icsFileContents)
        return calendar

