from .Processor import Processor
from ics import Calendar

class AlterMetaDataProcessor(Processor):

    icsFileName = "GenCal Calendar"
    icsFileDescription = "This calendar was generated by the Gencal App"
    
    def process(self, calendar):
        icsFileContents = "\r\n".join(
           f"X-WR-CALNAME:{self.icsFileName}" if line.startswith("X-WR-CALNAME") 
           else f"NAME:{self.icsFileName}" if line.startswith("NAME") 
           else f"X-WR-CALDESC:{self.icsFileDescription}" if line.startswith("X-WR-CALDESC") 
           else line
           for line in calendar.serialize().splitlines()
           )
        calendar = Calendar(icsFileContents)
        return calendar