from .Processor import Processor
from ics import Calendar

class AlterMetaDataProcessor(Processor):
    
    def process(self, calendar):
        icsFileName = "GenCal Calendar"
        icsFileDescription = "This calendar was generated by the Gencal App"
        icsFileContents = "\r\n".join(
           f"X-WR-CALNAME:{icsFileName}" if line.startswith("X-WR-CALNAME") 
           else f"NAME:{icsFileName}" if line.startswith("NAME") 
           else f"X-WR-CALDESC:{icsFileDescription}" if line.startswith("X-WR-CALDESC") 
           else line
           for line in calendar.serialize().splitlines()
           )
        calendar = Calendar(icsFileContents)
        return calendar